spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/asset_management_system
spring.datasource.username=root
spring.datasource.password=Ninetails@1705
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sageassets8@gmail.com

# Use your 16-character Google App Password here (Do not use spaces)
spring.mail.password=cutw nylo cmur rbhy

# Technical Security Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Connection timeouts to prevent background worker lockups
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000